server {
    listen 80;
    server_name .trendforus.site www.trendforus.site;
    return 301 https://$host#request_uri;
    }

server {
    listen 443 ssl;
    server_name .trendforus.site www.trendforus.site;
    charset utf-8;
    client_max_body_size 128M;
    autoindex off;

    ssl_certificate /etc/letsencrypt/live/trendforus.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/trendforus.site/privkey.pem;

    location / {
        uwsgi_pass  unix:///tmp/TrendforUs.sock;
        include     uwsgi_params;
    }
    location /static/ {
	alias /home/ubuntu/srv/TrendforUs/static/;
    }
}
